--- 
title: "My Notes on Ula&Smith (2009) Paper "
author: "Peyman Kor"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [Phd-Literature.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Abstract

Consumers or firms contemplating purchasing a new product or adopting a new technology are often plagued by uncertainty: Will the benefits outweigh the costs? Should we buy now or wait and gather more information? In this paper, we study a dynamic programming model of this technology adoption problem. In each period, the consumer decides whether to adopt the technology, reject it, or wait and gather additional information by observing a signal about the technology’s benefit. The technology’s actual benefit may be constant or changing stochastically over time. The dynamic programming state variable is a probability distribution that describes the consumer’s beliefs about the benefits of the technology. We allow general probability distributions on benefits and general signal processes and assume that the consumer updates her beliefs over time using Bayes’ rule. We are interested in structural properties of this model. We show that improving the technology’s benefit need not make the consumer better off and that first-order stochastic dominance improvements in the consumer’s distribution on benefits need not increase the consumer’s value function. Nevertheless, the model possesses a great deal of structure. For example, we obtain monotonic value functions and policies if we order distributions using
likelihood-ratio dominance rather than first-order stochastic dominance. We also examine convexity properties and provide many comparative statics results.
